config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('yolo/', include('yolo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

handler404 = 'common.views.page_not_found'

pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views, vote_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    # comment_views.py
    path('comment/create/question/<int:question_id>/', comment_views.comment_create_question, name='comment_create_question'),
    path('comment/modify/question/<int:comment_id>/', comment_views.comment_modify_question, name='comment_modify_question'),
    path('comment/delete/question/<int:comment_id>/', comment_views.comment_delete_question, name='comment_delete_question'),
    path('comment/create/answer/<int:answer_id>/', comment_views.comment_create_answer, name='comment_create_answer'),
    path('comment/modify/answer/<int:comment_id>/', comment_views.comment_modify_answer, name='comment_modify_answer'),
    path('comment/delete/answer/<int:comment_id>/', comment_views.comment_delete_answer, name='comment_delete_answer'),
    # vote_views.py
    path('vote/question/<int:question_id>/', vote_views.vote_question, name='vote_question'),
    path('vote/answer/<int:answer_id>/', vote_views.vote_answer, name='vote_answer'),
]

yolo/urls.py
from django.urls import path
from .views import yolo_base_views, yolo_question_views, yolo_answer_views, yolo_comment_views, yolo_vote_views
# from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'yolo'

urlpatterns = [
    # path('', views.index, name='index'),
    # base_views.py
    path('', yolo_base_views.yolo_index, name='yolo_index'),
    path('<int:yolo_question_id>/', yolo_base_views.yolo_detail, name='yolo_detail'),
    # question_views.py
    path('question/create/', yolo_question_views.yolo_question_create, name='yolo_question_create'),
    path('question/modify/<int:yolo_question_id>/', yolo_question_views.yolo_question_modify, name='yolo_question_modify'),
    path('question/delete/<int:yolo_question_id>/', yolo_question_views.yolo_question_delete, name='yolo_question_delete'),
    # answer_views.py
    path('answer/create/<int:yolo_question_id>/', yolo_answer_views.yolo_answer_create, name='yolo_answer_create'),
    path('answer/modify/<int:yolo_answer_id>/', yolo_answer_views.yolo_answer_modify, name='yolo_answer_modify'),
    path('answer/delete/<int:yolo_answer_id>/', yolo_answer_views.yolo_answer_delete, name='yolo_answer_delete'),
    # comment_views.py
    path('comment/create/question/<int:yolo_question_id>/', yolo_comment_views.yolo_comment_create_question, name='yolo_comment_create_question'),
    path('comment/modify/question/<int:yolo_comment_id>/', yolo_comment_views.yolo_comment_modify_question, name='yolo_comment_modify_question'),
    path('comment/delete/question/<int:yolo_comment_id>/', yolo_comment_views.yolo_comment_delete_question, name='yolo_comment_delete_question'),
    path('comment/create/answer/<int:yolo_answer_id>/', yolo_comment_views.yolo_comment_create_answer, name='yolo_comment_create_answer'),
    path('comment/modify/answer/<int:yolo_comment_id>/', yolo_comment_views.yolo_comment_modify_answer, name='yolo_comment_modify_answer'),
    path('comment/delete/answer/<int:yolo_comment_id>/', yolo_comment_views.yolo_comment_delete_answer, name='yolo_comment_delete_answer'),
    # vote_views.py
    path('vote/question/<int:yolo_question_id>/', yolo_vote_views.yolo_vote_question, name='yolo_vote_question'),
    path('vote/answer/<int:yolo_answer_id>/', yolo_vote_views.yolo_vote_answer, name='yolo_vote_answer'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

yolo/models.py
from django.db import models
from django.contrib.auth.models import User

class YQuestion(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    imgfile = models.ImageField(null=True, upload_to="yolo/question/%Y%m%d", blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question_yolo')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question_yolo')
    def __str__(self):
        return self.subject

class YAnswer(models.Model):
    question = models.ForeignKey(YQuestion, on_delete=models.CASCADE)
    content = models.TextField()
    imgfile = models.ImageField(null=True, upload_to="", blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer_yolo')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer_yolo')

class YComment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='voter_comment_yolo')
    content = models.TextField()
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    question = models.ForeignKey(YQuestion, null=True, blank=True, on_delete=models.CASCADE)
    answer = models.ForeignKey(YAnswer, null=True,blank=True,on_delete=models.CASCADE)

yolo/forms.py
from django import forms
from yolo.models import YQuestion, YAnswer, YComment

class YQuestionForm(forms.ModelForm):
    class Meta:
        model = YQuestion
        fields = ['subject', 'content', 'imgfile']
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows':10}),
        # }
        labels = {
            'subject': '제목',
            'content': '내용',
            'imgfile': '업로드 파일',
        }

class YAnswerForm(forms.ModelForm):
    class Meta:
        model = YAnswer
        fields = ['content', 'imgfile']
        labels = {
            'content': '답변내용',
            'imgfile': '업로드 파일',
        }

class YCommentForm(forms.ModelForm):
    class Meta:
        model = YComment
        fields = ['content']
        labels = {
            'content': '댓글내용'
        }

yolo/views/yolo_answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..models import YQuestion, YAnswer
from ..forms import YAnswerForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.

@login_required(login_url='common:login')
def yolo_answer_create(request, yolo_question_id, yolo_predict_file, yolo_result):
    yolo_question = get_object_or_404(YQuestion, pk=yolo_question_id)
    if request.method == 'POST':
        form = YAnswerForm(request.POST)
        if form.is_valid():
            yolo_answer = form.save(commit=False)
            yolo_answer.content = yolo_result
            yolo_answer.imgfile = yolo_predict_file
            yolo_answer.author = request.user
            yolo_answer.create_date = timezone.now()
            yolo_answer.question = yolo_question
            yolo_answer.save()
            return redirect('{}#yolo_answer_{}'.format(
                resolve_url('yolo:yolo_detail', yolo_question_id=yolo_question.id), yolo_answer.id))
    else:
        form = YAnswerForm()
    context = {'yolo_question': yolo_question, 'form': form}
    return render(request, 'yolo/yolo_question_detail.html', context)

@login_required(login_url='common:login')
def yolo_answer_modify(request, yolo_answer_id):
    yolo_answer = get_object_or_404(YAnswer, pk=yolo_answer_id)
    if request.user != yolo_answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('yolo:yolo_detail', yolo_question_id=yolo_answer.question.id)
    if request.method == 'POST':
        form = YAnswerForm(request.POST, instance=yolo_answer)
        if form.is_valid():
            yolo_answer = form.save(commit=False)
            yolo_answer.author = request.user
            yolo_answer.modify_date = timezone.now()
            yolo_answer.save()
            return redirect('{}#yolo_answer_{}'.format(
                resolve_url('yolo:yolo_detail', yolo_question_id=yolo_answer.question.id), yolo_answer.id))
    else:
        form = YAnswerForm(instance=yolo_answer)
    context = {'yolo_answer': yolo_answer, 'form': form}
    return render(request, 'yolo/yolo_answer_form.html', context)

@login_required(login_url='common:login')
def yolo_answer_delete(request, yolo_answer_id):
    yolo_answer = get_object_or_404(YAnswer, pk=yolo_answer_id)
    if request.user != yolo_answer.author:
        messages.error(request, '삭제권한이 없습니다.')
    else:
        messages.error(request, '삭제권한이 있습니다.')
        yolo_answer.delete()
    return redirect('yolo:yolo_detail', yolo_question_id=yolo_answer.question.id)

yolo/views/yolo_base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404
from django.db.models import Q, Count
from ..models import YQuestion
import logging
loger = logging.getLogger('yolo')

# Create your views here.
def yolo_index(request):
    # loger.info("INFO 레벨로 출력")
    # 입력인자
    page = request.GET.get('page', 1)
    kw = request.GET.get('kw', '')
    so = request.GET.get('so', 'recent')
    # 정렬
    if so == 'recommend':
        yolo_question_list = (YQuestion.objects.annotate(num_voter=Count('voter'))
                              .order_by('-num_voter', '-create_date'))
    elif so == 'popular':
        yolo_question_list = (YQuestion.objects.annotate(num_answer=Count('yanswer'))
                              .order_by('-num_answer', '-create_date'))
    else:   # recent
        yolo_question_list = YQuestion.objects.order_by('-create_date')
    # 조회
    # question_list = Question.objects.order_by('-create_date')
    if kw:
        yolo_question_list = yolo_question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(yanswer__author__username__icontains=kw)
        ).distinct()

    # 페이징 처리
    paginator = Paginator(yolo_question_list, 10)
    page_obj = paginator.get_page(page)

    context = {'yolo_question_list': page_obj, 'page': page, 'kw': kw, 'so': so}
    return render(request, 'yolo/yolo_question_list.html', context)

def yolo_detail(request, yolo_question_id):
    yolo_question = get_object_or_404(YQuestion, pk=yolo_question_id)
    context = {'yolo_question':yolo_question}
    return render(request, 'yolo/yolo_question_detail.html', context)

yolo/views/yolo_comment_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from ..models import YQuestion, YAnswer, YComment
from ..forms import YCommentForm
from django.contrib.auth.decorators import login_required
from django.contrib import messages

# Create your views here.
@login_required(login_url='common:login')
def yolo_comment_create_question(request, yolo_question_id):
    yolo_question = get_object_or_404(YQuestion, pk=yolo_question_id)
    if request.method == "POST":
        form = YCommentForm(request.POST)
        if form.is_valid():
            yolo_comment = form.save(commit=False)
            yolo_comment.author = request.user
            yolo_comment.create_date = timezone.now()
            yolo_comment.question = yolo_question
            yolo_comment.save()
            return redirect('{}#yolo_comment_{}'.format(resolve_url('yolo:yolo_detail',
                yolo_question_id=yolo_comment.question.id), yolo_comment.id))
    else:
        form = YCommentForm()
    context = {'form': form}
    return render(request, 'yolo/yolo_comment_form.html', context)

@login_required(login_url='common:login')
def yolo_comment_modify_question(request, yolo_comment_id):
    yolo_comment = get_object_or_404(YComment, pk=yolo_comment_id)
    if request.user != yolo_comment.author:
        messages.error(request, '댓글수정권한이 없습니다.')
        return redirect('yolo:yolo_detail', yolo_question_id=yolo_comment.question.id)
    if request.method == 'POST':
        form = YCommentForm(request.POST, instance=yolo_comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#yolo_comment_{}'.format(resolve_url('yolo:yolo_detail',
                yolo_question_id=yolo_comment.question.id), yolo_comment.id))
    else:
        form = YCommentForm(instance=yolo_comment)
    context = {'form': form}
    return render(request, 'yolo/yolo_comment_form.html', context)

@login_required(login_url='common:login')
def yolo_comment_delete_question(request, yolo_comment_id):
    yolo_comment = get_object_or_404(YComment, pk=yolo_comment_id)
    if request.user != yolo_comment.author:
        messages.error(request, '댓글삭제권한이 없습니다.')
        return redirect('yolo:yolo_detail', yolo_question_id=yolo_comment.question.id)
    else:
        yolo_comment.delete()
    return redirect('yolo:yolo_detail', yolo_question_id=yolo_comment.question.id)

@login_required(login_url='common:login')
def yolo_comment_create_answer(request, yolo_answer_id):
    """
    pybo 답글댓글등록
    """
    yolo_answer = get_object_or_404(YAnswer, pk=yolo_answer_id)
    if request.method == "POST":
        form = YCommentForm(request.POST)
        if form.is_valid():
            yolo_comment = form.save(commit=False)
            yolo_comment.author = request.user
            yolo_comment.create_date = timezone.now()
            yolo_comment.answer = yolo_answer
            yolo_comment.save()
            return redirect('{}#yolo_comment_{}'.format(resolve_url('yolo:yolo_detail',
                yolo_question_id=yolo_comment.answer.question.id), yolo_comment.id))
    else:
        form = YCommentForm()
    context = {'form': form}
    return render(request, 'yolo/yolo_comment_form.html', context)


@login_required(login_url='common:login')
def yolo_comment_modify_answer(request, yolo_comment_id):
    yolo_comment = get_object_or_404(YComment, pk=yolo_comment_id)
    if request.user != yolo_comment.author:
        messages.error(request, '댓글수정권한이 없습니다')
        return redirect('yolo:yolo_detail', yolo_question_id=yolo_comment.answer.question.id)

    if request.method == "POST":
        form = YCommentForm(request.POST, instance=yolo_comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('{}#yolo_comment_{}'.format(resolve_url('yolo:yolo_detail',
                yolo_question_id=yolo_comment.answer.question.id), yolo_comment.id))
    else:
        form = YCommentForm(instance=yolo_comment)
    context = {'form': form}
    return render(request, 'yolo/yolo_comment_form.html', context)

@login_required(login_url='common:login')
def yolo_comment_delete_answer(request, yolo_comment_id):
    yolo_comment = get_object_or_404(YComment, pk=yolo_comment_id)
    if request.user != yolo_comment.author:
        messages.error(request, '댓글삭제권한이 없습니다')
        return redirect('yolo:yolo_detail', yolo_question_id=yolo_comment.answer.question.id)
    else:
        yolo_comment.delete()
    return redirect('yolo:yolo_detail', yolo_question_id=yolo_comment.answer.question.id)

yolo/views/yolo_vote_views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from ..models import YQuestion, YAnswer

# Create your views here.
@login_required(login_url='common:login')
def yolo_vote_question(request, yolo_question_id):
    yolo_question = get_object_or_404(YQuestion, pk=yolo_question_id)
    if request.user == yolo_question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        yolo_question.voter.add(request.user)
    return redirect('yolo:yolo_detail', yolo_question_id=yolo_question.id)

@login_required(login_url='common:login')
def yolo_vote_answer(request, yolo_answer_id):
    yolo_answer = get_object_or_404(YAnswer, pk=yolo_answer_id)
    if request.user == yolo_answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        yolo_answer.voter.add(request.user)
    return redirect('yolo:yolo_detail', yolo_question_id=yolo_answer.question.id)

templates/yolo/yolo_answer_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container my-3">
    <form method="post" class="post-form">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">답변내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/yolo/yolo_comment_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container my-3">
    <h5 class="border-bottom pb-2">댓글등록하기</h5>
    <form method="post" class="post-form my-3">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="form-group">
            <label for="content">댓글내용</label>
            <textarea class="form-control" name="content" id="content" rows="3">
                {{ form.content.value|default_if_none:'' }}
            </textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/yolo/yolo_question_detail.html
{% extends 'base.html' %}
{% load yolo_filter %}
{% block content %}
<div class="container my-3">
    <!-- 사용자오류 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
    {% endif %}
    <h2 class="border-bottom py-2">{{ yolo_question.subject }}</h2>
    <div class="row my-3">
        <div class="col-1"> <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ yolo_question.voter.count }}</div>
            <a href="#" data-uri="{% url 'yolo:yolo_vote_question' yolo_question.id  %}"
               class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11"> <!-- 질문영역 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text">{{ yolo_question.content|mark }}</div>
                    <img src="..{{ yolo_question.imgfile.url }}" width="500">
                    <!--div class="card-text">{{ yolo_question.imgfile }}</div-->
                    <div class="d-flex justify-content-end">
                        {% if yolo_question.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ yolo_question.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ yolo_question.author.username }}</div>
                            <div>{{ yolo_question.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == yolo_question.author %}
                    <div class="my-3">
                        <a href="{% url 'yolo:yolo_question_modify' yolo_question.id  %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary"
                           data-uri="{% url 'yolo:yolo_question_delete' yolo_question.id  %}">삭제</a>
                    </div>
                    {% endif %}
                    <!-- 질문 댓글 Start -->
                    {% if yolo_question.ycomment_set.count > 0 %}
                    <div class="mt-3">
                    {% for yolo_comment in yolo_question.ycomment_set.all %}
                        <a name="yolo_comment_{{ yolo_comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <!--<span style="white-space: pre-line;">{{ yolo_comment.content }}</span>-->
                            <span>{{ yolo_comment.content|mark }}</span>
                            <span>
                                - {{ yolo_comment.author }}, {{ yolo_comment.create_date }}
                                {% if yolo_comment.modify_date %}
                                (수정:{{ yolo_comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == yolo_comment.author %}
                            <a href="{% url 'yolo:yolo_comment_modify_question' yolo_comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'yolo:yolo_comment_delete_question' yolo_comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'yolo:yolo_comment_create_question' yolo_question.id  %}"
                           class="small"><small>댓글 추가 ..</small></a>
                    </div>
                    <!-- 질문 댓글 End -->
                </div>
            </div>
        </div>
    </div>
    <h5 class="border-bottom my-3 py-2">{{ yolo_question.yanswer_set.count }}개의 답변이 있습니다.</h5>
    {% for yolo_answer in yolo_question.yanswer_set.all %}
    <a name="yolo_answer_{{ yolo_answer.id }}"></a>
    <div class="row my-3">
        <div class="col-1">  <!-- 추천영역 -->
            <div class="bg-light text-center p-3 border font-weight-bolder mb-1">{{ yolo_answer.voter.count }}</div>
            <a href="#" data-uri="{% url 'yolo:yolo_vote_answer' yolo_answer.id  %}"
                class="recommend btn btn-sm btn-secondary btn-block my-1">추천</a>
        </div>
        <div class="col-11">  <!-- 답변영역 -->
            <div class="card">
                <div class="card-body">
                    <div class="card-text">{{ yolo_answer.content|mark }}</div>
                    <img src="..{{ yolo_answer.imgfile.url }}" width="500">
                    <!--div class="card-text">{{ yolo_answer.imgfile.path }}</div-->
                    <div class="d-flex justify-content-end">
                        {% if yolo_answer.modify_date %}
                        <div class="badge badge-light p-2 text-left mx-3">
                            <div class="mb-2">modified at</div>
                            <div>{{ yolo_answer.modify_date }}</div>
                        </div>
                        {% endif %}
                        <div class="badge badge-light p-2 text-left">
                            <div class="mb-2">{{ yolo_answer.author.username }}</div>
                            <div>{{ yolo_answer.create_date }}</div>
                        </div>
                    </div>
                    {% if request.user == yolo_answer.author %}
                    <div class="my-3">
                        <a href="{% url 'yolo:yolo_answer_modify' yolo_answer.id  %}"
                           class="btn btn-sm btn-outline-secondary">수정</a>
                        <a href="#" class="delete btn btn-sm btn-outline-secondary "
                           data-uri="{% url 'yolo:yolo_answer_delete' yolo_answer.id  %}">삭제</a>
                    </div>
                    {% endif %}
                    {% if yolo_answer.ycomment_set.count > 0 %}
                    <div class="mt-3">
                    {% for yolo_comment in yolo_answer.ycomment_set.all %}
                        <a name="yolo_comment_{{ yolo_comment.id }}"></a>
                        <div class="comment py-2 text-muted">
                            <!--<span style="white-space: pre-line;">{{ comment.content }}</span>-->
                            <span>{{ yolo_comment.content|mark }}</span>
                            <span>
                                - {{ yolo_comment.author }}, {{ yolo_comment.create_date }}
                                {% if yolo_comment.modify_date %}
                                (수정:{{ yolo_comment.modify_date }})
                                {% endif %}
                            </span>
                            {% if request.user == yolo_comment.author %}
                            <a href="{% url 'yolo:yolo_comment_modify_answer' yolo_comment.id  %}" class="small">수정</a>,
                            <a href="#" class="small delete"
                               data-uri="{% url 'yolo:yolo_comment_delete_answer' yolo_comment.id  %}">삭제</a>
                            {% endif %}
                        </div>
                    {% endfor %}
                    </div>
                    {% endif %}
                    <div>
                        <a href="{% url 'yolo:yolo_comment_create_answer' yolo_answer.id  %}"
                           class="small"><small>댓글 추가 ..</small></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    <form action="{% url 'yolo:yolo_answer_create' yolo_question.id %}" method="post" class="my-3">
        {% csrf_token %}
        {% if form.errors %}
        <div class="alert alert-danger" role="alert">
        {% for field in form %}
            {% if field.errors %}
            <strong>{{ field.label }}</strong>
            {{ field.errors }}
            {% endif %}
        {% endfor %}
        </div>
        {% endif %}
        <div class="form-group">
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
              name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".delete").on('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
    $(".recommend").on('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = $(this).data('uri');
        }
    });
});
</script>
{% endblock %}

templates/yolo/yolo_question_form.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">요청 등록</h5>
    <form method="post" class="post-form my-3" action="{% url 'yolo:yolo_question_create' %}" enctype="multipart/form-data">
        {% csrf_token %}
<!--        {{form.as_p}}-->
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
                {% for field in form %}
                    {% if field.errors %}
                    <strong>{{field.label}}</strong>
                    {{field.errors}}
                    {% endif %}
                {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->
        <div class="form-group">
            <label for="subject">제목</label>
            <input type="text" class="form-control" name="subject" id="subject"
                   value="{{form.subject.value|default_if_none:''}}">
        </div>
        <div class="form-group">
            <label for="content">내용</label>
            <textarea class="form-control" name="content" id="content" rows="10">
                {{form.content.value|default_if_none:''}}
            </textarea>
        </div>
        <div class="form-group">
            <input type="file" name="imgfile" id="imgfile">
        </div>
        <button type="submit" class="btn btn-primary">등록하기</button>
    </form>
</div>
{% endblock %}